services:
  ffmpeg-mcp:
    build: .
    container_name: ffmpeg-mcp-server
    ports:
      - "8032:8032"
    volumes:
      # 请确保左侧路径正确
      - ./videos:/videos
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
